name: mMaintenance
main: fr.mathis.mm.mMaintenance
author: Mathis Audureau
version: 1.0.0
api-version: 1.0.0
commands:
  maintenance:
    description: "Commande permettant de passer le serveur en phase de maintenance."
